"use strict";this.default_AccountsSignInUi=this.default_AccountsSignInUi||{};(function(_){var window=this;
try{
var Dva=function(a,b){this.da=a;this.ha=b;if(!c){var c=new _.Dg("//www.google.com/images/cleardot.gif");_.Om(c)}this.oa=c};_.h=Dva.prototype;_.h.Md=null;_.h.f4=1E4;_.h.gE=!1;_.h.dW=0;_.h.qP=null;_.h.F_=null;_.h.setTimeout=function(a){this.f4=a};_.h.start=function(){if(this.gE)throw Error("rc");this.gE=!0;this.dW=0;Eva(this)};_.h.stop=function(){Fva(this);this.gE=!1};
var Eva=function(a){a.dW++;navigator!==null&&"onLine"in navigator&&!navigator.onLine?_.eo((0,_.th)(a.WL,a,!1),0):(a.aa=new Image,a.aa.onload=(0,_.th)(a.vqa,a),a.aa.onerror=(0,_.th)(a.uqa,a),a.aa.onabort=(0,_.th)(a.tqa,a),a.qP=_.eo(a.wqa,a.f4,a),a.aa.src=String(a.oa))};_.h=Dva.prototype;_.h.vqa=function(){this.WL(!0)};_.h.uqa=function(){this.WL(!1)};_.h.tqa=function(){this.WL(!1)};_.h.wqa=function(){this.WL(!1)};
_.h.WL=function(a){Fva(this);a?(this.gE=!1,this.da.call(this.ha,!0)):this.dW<=0?Eva(this):(this.gE=!1,this.da.call(this.ha,!1))};var Fva=function(a){a.aa&&(a.aa.onload=null,a.aa.onerror=null,a.aa.onabort=null,a.aa=null);a.qP&&(_.fo(a.qP),a.qP=null);a.F_&&(_.fo(a.F_),a.F_=null)};var Gva=function(){_.bo.call(this);this.aa=new Dva(this.zqa,this);this.ha=51E3+Math.round(18E3*Math.random())};_.J(Gva,_.bo);_.h=Gva.prototype;_.h.zqa=function(a){this.PZ=Date.now();this.J9(a)};_.h.J9=function(a){this.w9=a;this.dispatchEvent("g")};_.h.Md=null;_.h.PZ=0;_.h.w9=!0;var Hva=function(){this.aa=new Gva};_.ff(_.Lna,Hva);_.Eb().Bl(function(a){var b=new Hva(a);_.nq(a,_.Lna,b)});
_.k("byfTOb");

_.l();
_.k("lsjVmc");
var Ir=function(a,b){b=b===void 0?!0:b;_.Oi.call(this);this.wa=a;this.da=new _.Hr(this);b&&_.Iva(this);_.ph(this,this.da)};_.Ni(Ir,_.Oi);Ir.prototype.aa=null;Ir.prototype.ha="at";Ir.prototype.oa=null;_.Iva=function(a){var b=a.wa.get(_.Nl);b.wa.includes(a.da);b.oa(a.da)};Ir.prototype.configure=function(a,b,c){this.aa=a;this.oa=b;c&&(this.ha=c)};_.Hr=function(a){this.ha=a};_.Ni(_.Hr,_.jg);_.Hr.prototype.aa=_.ba(8);_.Hr.prototype.da=_.ba(11);_.ff(_.Mna,Ir);_.Eb().Bl(function(a){var b=new Ir(a,!1);_.nq(a,_.Mna,b);b.configure(_.ug("SNlM0e").string(null),_.ug("S06Grb").string(null))});
_.l();
_.Rf.prototype.aR=_.ca(5,function(){return this.zy});_.Jr=function(a){var b=a.Ae().aR();if(b==null||b<0)return null;var c=_.vl[b];if(c){var d=Object.values(c)[0],e=_.cm(a,_.Ul);c=_.cm(a,_.zka);var f=_.cm(a,_.Vl),g=_.cm(a,_.Wl),m=_.cm(a,_.Aka);b=_.tl[b];a={Xn:d,Ct:b?Object.values(b)[0]:void 0,request:a.Gi(),jF:!!e};f&&(a.Q5=f);g&&(a.R5=g);c&&(a.uC=c);m&&(a.ZR=m);return a}return(c=_.wl[b])?(c=Object.values(c)[0],b=_.xl[b],{Xn:b?Object.values(b)[0]:void 0,yC:c,i_:a.Gi()}):null};
_.Kr=function(){this.aa=[];this.da=[]};_.Rf.prototype.ZJ=_.ca(4,function(){return this.Jra});var Jva=function(a){a.aa.length===0&&(a.aa=a.da,a.aa.reverse(),a.da=[])};_.Kr.prototype.enqueue=function(a){this.da.push(a)};_.Kva=function(a){Jva(a);return a.aa.pop()};_.Lva=function(a){Jva(a);return _.la(a.aa)};_.h=_.Kr.prototype;_.h.Jh=function(){return this.aa.length+this.da.length};_.h.He=function(){return this.aa.length===0&&this.da.length===0};_.h.clear=function(){this.aa=[];this.da=[]};
_.h.contains=function(a){return _.ta(this.aa,a)||_.ta(this.da,a)};_.h.remove=function(a){var b=this.aa;var c=(0,_.Hha)(b,a);c>=0?(_.wa(b,c),b=!0):b=!1;return b||_.xa(this.da,a)};_.h.Ok=function(){for(var a=[],b=this.aa.length-1;b>=0;--b)a.push(this.aa[b]);b=this.da.length;for(var c=0;c<b;++c)a.push(this.da[c]);return a};
_.Lr=function(a){this.Ea=_.u(a)};_.J(_.Lr,_.w);_.Mr=function(a){return _.Sk(a,3,"0")};
_.Nr=function(a){if(a==null)return a;if(typeof a==="bigint")return a>=0&&(0,_.Qd)(a)?a=Number(a):(a=(0,_.wd)(64,a),a=(0,_.Qd)(a)?Number(a):String(a)),a;if(_.ed(a))return typeof a==="number"?_.td(a):_.ud(a)};_.Or=function(){return _.jp(_.ug("w2btAe"),_.Lr,new _.Lr)};_.Pr=function(){return _.ug("Im6cmf").string()};
var Qr,Nva,Rr,Pva,Qva,Rva,Sr,Sva,Tva,Tr,Vr,Wva,Wr,Xva,$va,Yr,awa,bwa,Mva;Qr=function(a,b){_.Pea(a,b,"unknown")};Nva=function(a){var b=_.nb.apply(1,arguments),c=a[0];if(a.length===1)return c+"_";c=[0,c];for(var d=0;d<b.length;d++){var e=b[d];"function"==typeof Mva&&e instanceof Mva?c.push(2,e.jqa):typeof e==="number"?c.push(2,String(e)):c.push(1,e);c.push(0,a[d+1])}return JSON.stringify(c)};_.Ova=function(a,b){if(b==null)return new a;b=_.tca(b);return new a(_.yba(b))};
Rr=function(a,b,c){a.push(encodeURIComponent(b)+"="+encodeURIComponent(c))};Pva=function(a){a=a.elements;for(var b,c=0;b=a[c];c++)if(!b.disabled&&b.type&&b.type.toLowerCase()=="file")return!0;return!1};
Qva=function(a){for(var b=[],c=a.elements,d,e,f=0;d=c.item(f);f++)if(d.form==a&&!d.disabled&&d.tagName!="FIELDSET")switch(e=d.name,d.type.toLowerCase()){case "file":case "submit":case "reset":case "button":break;case "select-multiple":d=_.Tfa(d);if(d!=null)for(var g,m=0;g=d[m];m++)Rr(b,e,g);break;default:d=_.Tfa(d),d!=null&&Rr(b,e,d)}c=a.getElementsByTagName("INPUT");for(d=0;f=c[d];d++)f.form==a&&f.type.toLowerCase()=="image"&&(e=f.name,Rr(b,e,f.value),Rr(b,e+".x","0"),Rr(b,e+".y","0"));return b.join("&")};
Rva=function(a){if(_.Xqa!==_.Xqa)throw Error();return new Mva(a)};Sr=function(a,b,c,d,e){this.da=a;this.aa=b;(b===void 0||b<=0)&&_.lg(Error("tc`"+b+"`"+(a&&a.ha.da)));this.wa=c==1;this.oa=d;this.ha=e};Sva=function(a){var b;if(a.length!==0&&typeof(b=a[0])==="string"&&b)return b};Tva=function(a,b,c,d){b!==-1&&(a+=" (HTTP Status: "+b+")");c&&(a+=" (XHR Error Code: "+c+") (XHR Error Message: '"+d+"')");return a};
Tr=function(a,b){this.aa=b;this.constructor.G5||(this.constructor.G5={});this.constructor.G5[this.toString()]=this};Vr=function(a){(this.Na=a)&&_.Ur(this,"BEST_EFFORT");_.Li();this.ha=new _.Dg;this.aa="POST";this.jh=Uva++;Vva||(a=new Date,Vva=a.getHours()*3600+a.getMinutes()*60+a.getSeconds());this.hb=1+Vva+this.jh*1E5;this.Ia=new _.Vp;this.wd=-1};Wva=function(){_.ka.call(this);this.message="Retryable Server Error"};
Wr=function(){_.bo.call(this);_.bo.call(this);this.Ia=new _.Kr;this.Ma=new _.Vp;this.aa=[];this.ha=[];this.oa=[];this.Xa=new _.Ro(this);new _.Vp;this.Sa=!0};Xva=function(a){this.Ea=_.u(a)};_.J(Xva,_.w);var Yva=function(a){this.Ea=_.u(a,0,Yva.messageId)};_.J(Yva,_.w);Yva.messageId="xsrf";var Zva=_.Ke(48448350,_.yl,Yva),Xr=function(){_.ka.call(this);this.message="XSRF token refresh"};_.J(Xr,_.ka);_.jg.prototype.da=_.ca(12,function(){});
_.Hr.prototype.da=_.ca(11,function(a){for(var b=0;b<a.length;b++){var c=void 0,d=(c=a[b].aa())==null?void 0:_.rka(c,Zva);if(c=d){c=this.ha;var e=!1,f=void 0,g=c.oa;_.K(d,Xva,2,_.Tc)&&(f=_.K(d,Xva,2,_.Tc),f=_.bl(f,1));g&&f===g&&(c.aa=_.bl(d,1,_.Tc),e=!0);c=e}if(c)throw new Xr;}});_.jg.prototype.aa=_.ca(10,function(){});_.epa.prototype.aa=_.ca(9,function(a){var b=_.Em(_.no().location.href,"TL");b&&a.oa("TL",b)});
_.Hr.prototype.aa=_.ca(8,function(a){var b=this.ha;if(b.ha&&b.aa)if(a.aa=="DELETE")a.Wb(b.aa);else{var c=b.ha;b=b.aa;var d=a.wa;d?(a=d.elements[c],a||(a=d.ownerDocument.createElement("input"),a.setAttribute("name",c),a.setAttribute("hidden",!0),d.appendChild(a)),a.value=b):a.Vb||a.Da(c,b)}});$va=function(a,b,c){typeof b==="function"?_.Qi(c)||b.call(c):b&&typeof b.handleEvent=="function"&&(_.Qi(b)||b.handleEvent.call(b))};
Yr=function(a,b,c,d){var e=typeof b==="function";(e||!_.Qi(b))&&e&&_.Qi(d);if(!(e||b&&typeof b.handleEvent=="function"))throw Error("La");a=(0,_.th)($va,null,a,b,d);return _.fa.setTimeout(a,c||0)};awa={};bwa=function(a){return _.pja(awa,a,function(){return _.Zb(_.Mj,a)>=0})};_.cwa={value:3,w$:!0};Mva=function(a){this.jqa=a};Sr.prototype.Sn=function(){return this.ha};
var dwa=function(a){if(a.wa)a=!1;else{var b;if(b=!!a.da)a:switch(b=a.da,b.rJ){case "RETRY":b=!0;break a;case "FAIL":b=!1;break a;case "BEST_EFFORT":b=a.oa||a.da.hI;b=a.aa>=500&&b<3?!0:!1;break a;default:throw Error("uc`"+b.rJ);}a=b}return a};Sr.prototype.toString=function(){return String(this.aa)};_.Zr=function(a,b,c,d,e){_.ka.call(this,"Error code = "+b+(c?", Path = "+c:"")+(d?", Message = "+d:"")+(e?", "+e.Sn():""));this.name=a;this.da=b;this.wp=e};_.J(_.Zr,_.ka);_.Zr.prototype.getError=function(){return this.wp};
var ewa=function(a,b){a=a.map(function(c){return c.messageId}).join(", ");b=b.map(function(c){c=c instanceof _.w?c.constructor.messageId:Array.isArray(c)&&c.length?c[0]instanceof _.w?c[0].constructor.messageId:Array.isArray(c[0])?Sva(c[0]):Sva(c):void 0;return c}).join(", ");return"Expected protos: ["+a+"]. Returned protos: ["+b+"]."},fwa=function(a,b,c){_.Zr.call(this,"TooManyProtosError",108,c,"The RequestService interface only supports a single received proto (be it data or error). "+(a&&b?ewa(a,
b):""))};_.J(fwa,_.Zr);var gwa=function(a,b,c){_.Zr.call(this,"ExpectedProtoNotFound",109,c,"The expected response proto was not returned by the server."+ewa(a,b))};_.J(gwa,_.Zr);var hwa=function(){_.Zr.call(this,"Retry",0,void 0,"An interceptor has requested that the request be retried.")};_.J(hwa,_.Zr);_.$r=function(a){this.Ea=_.u(a,0,_.$r.messageId)};_.J(_.$r,_.w);_.$r.prototype.Sn=function(){return _.bl(this,2,_.Tc)};_.$r.prototype.getData=function(){return _.bl(this,4,_.Tc)};
_.$r.prototype.aa=function(){return _.K(this,_.yl,10,_.Tc)};_.$r.messageId="er";_.iwa=_.vda(_.$r);var as=function(a){this.Ea=_.u(a,0,as.messageId)};_.J(as,_.w);as.messageId="di";var bs=function(a){this.Ea=_.u(a,0,bs.messageId)};_.J(bs,_.w);bs.messageId="e";var cs=function(a){this.Ea=_.u(a,0,cs.messageId)};_.J(cs,_.w);cs.messageId="f.ri";var ds=function(){_.Oi.call(this);this.ha=!1};_.J(ds,_.Oi);ds.prototype.I0=function(){return 0};ds.prototype.transfer=function(a){this.aa.HP(a);this.da=a};var jwa=function(a,b){switch(a){case 1:case 3:return 8;case 4:return NaN;case 7:return 100;case 6:return b||7;case 8:return 101;case 5:return 9;default:return 102}};var es=function(a){ds.call(this);this.Tm=new _.Xo;this.xG=a;this.Ia=null;this.Tm.headers.set("X-Same-Domain","1");_.Wn(this.Tm,"complete",this.c8,!1,this);_.Wn(this.Tm,"ready",this.d8,!1,this)};_.J(es,ds);_.h=es.prototype;_.h.Nd=function(){_.Zn(this.Tm,"complete",this.c8,!1,this);_.Zn(this.Tm,"ready",this.d8,!1,this);this.Tm.dispose();ds.prototype.Nd.call(this)};
_.h.transfer=function(a){this.aa.HP(a);this.da=a;a.oa("rt",this.xG);var b=a.Ia,c=a.Ma!=null||a.wa!=null;if(!a.Vb||c){if(this.oa&&(c=this.Sa.call(null),c!==void 0)){var d=a.wa;if(d){var e=d.elements[this.oa];e||(e=d.ownerDocument.createElement("input"),e.setAttribute("name",this.oa),e.setAttribute("hidden",!0),d.appendChild(e));e.value=c}else a.Da(this.oa,c)}this.Tm.send(a.getUrl(),a.aa,kwa(a),b)}else this.Tm.send(a.getUrl(),a.aa,null,b)};_.h.abort=function(a){this.Ia=a;this.Tm.abort(7)};
_.h.c8=function(a){a=a.target;this.da.Lc=a.getStatus();if(_.ap(a)){if(_.bp(a).length>0||a.getStatus()==204){this.e8(a);return}this.Ia=104}this.lK(a)};_.h.d8=function(){this.aa.Ata(this)};var kwa=function(a){var b=a.Ma;if(b){var c=new _.Ch;b.forEach(function(d,e){c.append(_.fm(e),"=",_.fm(d),"&")});return c.toString()}return a.wa?Qva(a.wa):""};
es.prototype.lK=function(a){var b=this.Ia;this.Ia=0;var c=a.getStatus(),d=a.nt;lwa.exec(_.bp(a));if(b)var e=b;else d==6&&(a=_.bp(a),e=(b=a.match(mwa))?700+parseInt(b[1],10):(b=a.match(nwa))?Number("6"+b[1]):null);e||(e=jwa(d,c));owa(this,e)};
var owa=function(a,b,c){var d=a.da;b=new Sr(d,b,void 0,void 0,c);a.aa.HS(d,b)},mwa=RegExp("var gmail_error\\s*=\\s*(\\d+)","m"),nwa=RegExp("var rc\\s*=\\s*(\\d+)","m"),lwa=RegExp("(?:Additional details|Detailed Technical Info)[\\s\\S]*<pre[^>]*>([\\s\\S]*)<\\/pre>","i");_.fs=function(){es.call(this,"c",null);this.Na=!1;_.Wn(this.Tm,"readystatechange",this.W7,!1,this);this.Qr=-1;this.Da=null;this.Ma=!0};_.J(_.fs,es);_.h=_.fs.prototype;_.h.clone=function(){var a=new _.fs,b=this.Sa;a.oa=this.oa;a.Sa=b;this.Na&&(a.Na=!0);return a};_.h.Nd=function(){_.fo(this.Qr);_.Zn(this.Tm,"readystatechange",this.W7,!1,this);es.prototype.Nd.call(this)};_.h.I0=function(a){if(a.P$)return 0;var b=a.wa;return b&&Pva(b)||_.gh&&!bwa("420+")||_.hh&&!bwa("1.9")?0:a.Ya||!a.VR?.9:.5};
_.h.W7=function(){_.gh||_.hh||_.Hj||_.fo(this.Qr);_.$o(this.Tm)==3&&this.vR(!1)};_.h.e8=function(){_.fo(this.Qr);this.vR(!0)};_.h.lK=function(a){var b=this.Na&&a.getStatus()>=500;this.vR(!0,b,a.getStatus(),a.nt,a.sF());es.prototype.lK.call(this,a)};
_.h.vR=function(a,b,c,d,e){c=c===void 0?-1:c;d=d===void 0?0:d;e=e===void 0?"":e;if(!this.Ya||a){var f=_.bp(this.Tm);if(this.wa==0){var g=f.indexOf("\n\n");if(g==-1){a&&(a=Tva("Incomplete XSS header at end of request",c,d,e),b||(c===0&&d===6?owa(this,7,Tva("Unknown HTTP error in underlying XHR",c,d,e)):owa(this,103,a)),this.Ma=!0);return}this.wa=g+2}do g=pwa(this,f);while(g==0);a&&(this.Ma=!0);switch(g){case 2:a?b||this.abort(10):this.Ya=!0;break;case 3:a&&(this.aa.VL(this.da,this.Tm.aK()),this.Ya&&
Qr("Chunk parse error: "+this.Xa+(this.Da?", "+this.Da:""),Error()));break;case 1:a&&(c=Tva("Incomplete chunk at end of request.",c,d,e),b||owa(this,103,c))}a||_.gh||_.hh||_.Hj||(this.Qr=_.eo(this.vR,100,this))}};_.h.transfer=function(a){this.Ma||Qr("transfer() called during response processing",Error());this.Ma=!1;this.wa=0;this.Ya=!1;es.prototype.transfer.call(this,a)};
var pwa=function(a,b){var c=a.wa;if(c==b.length)return 3;var d=b.indexOf("\n",c);if(d==-1)return 1;if(c==d)return a.Xa=0,a.Da=null,2;var e=b.substring(c,d),f=Number(e);if(isNaN(f))return a.Xa=1,a.Da="length: "+e.length+", "+e.substring(0,7)+", ssi:"+c+", sei:"+d+", rtl:"+b.length+", "+b.substring(0,Math.min(15,c)),2;if(d+f>b.length)return 1;c=b.substr(d,f);try{var g=window.JSON.parse(c)}catch(m){return a.Xa=2,a.Da=null,2}a.wa=d+f;if(Array.isArray(g))for(d=0;d<g.length;d++)a.aa.Ina(a.da,g[d]);return a.wa==
b.length?3:0};var qwa=function(a){this.uu=a};_.J(qwa,_.jg);qwa.prototype.aa=function(a){this.uu&&a.oa("bl",this.uu)};var rwa=function(a,b){var c={};_.Ma(a,function(d){var e=_.Em(b,d);e&&(c[d]=e)});this.ha=c};_.J(rwa,_.jg);rwa.prototype.aa=function(a){_.Fb(this.ha,function(b,c){_.Fg(a.ha,c)||a.oa(c,b)})};var swa=function(a){this.ha=[].slice.apply(arguments)};_.J(swa,_.jg);swa.prototype.aa=function(){_.Ma(this.ha,function(){})};var twa=function(a){this.ha=a};_.J(twa,_.jg);twa.prototype.aa=function(a){this.ha&&a.oa("f.sid",this.ha)};Tr.prototype.Ce=function(){return this.toString()};Tr.prototype.toString=function(){this.da||(this.da="lib:"+this.aa);return this.da};Tr.prototype.getType=function(){return this.aa};var uwa=function(a,b){Tr.call(this,a,b)};_.J(uwa,Tr);var vwa=new function(){};var wwa=function(a){a?(this.aa=_.Eh(_.Dk(a,1,_.Tc))||-1,_.bl(a,2,_.Tc),_.bl(a,3,_.Tc),_.Eh(_.Dk(a,4,_.Tc)),this.da=_.bl(a,13,_.Tc)||""):(this.aa=-1,this.da="")},xwa=new wwa;var Vva,ywa=new uwa(vwa,"f_req"),Uva=0;_.h=Vr.prototype;_.h.Md=null;_.h.P$=!0;_.h.VR=!0;_.h.rP=-1;_.h.g4=-1;_.h.i7=-1;_.h.Y8=-1;_.h.bT=xwa;_.h.t6=-1;_.h.hI=0;_.h.rJ="BEST_EFFORT";_.gs=function(a){if(a.started)throw Error("vc");};_.Ur=function(a,b){_.gs(a);a.rJ=b};Vr.prototype.Wb=function(a){this.Ia.set("X-Framework-Xsrf-Token",a)};Vr.prototype.getContext=function(){return this.xb};Vr.prototype.Cc=function(){this.rJ="FAIL";this.Na.abort(this,101)};_.zwa=function(a,b){_.gs(a);a.P$=b};_.h=Vr.prototype;
_.h.getMessage=function(){return""};_.h.send=function(){if(this.started)throw Error("yc");this.g4=_.Li();var a=this.oa;this.hb||Qr("No request id for ["+this.getUrl()+"]",Error("xc`"+this.getUrl()));a.call(this,"_reqid",this.hb);this.Na.send(this);this.started=!0;this.rP>=0&&(this.Sa=Yr("zc",this.Cc,this.rP,this))};_.h.abort=function(){if(!this.started)throw Error("Ac");this.complete||(this.rJ="FAIL",this.Na.abort(this))};_.h.Oj=function(){return!!this.complete};_.h.getType=function(){return ywa};
_.h.getData=function(a){return this.Cb?this.Cb[a]:null};var Awa=function(a){return!!a.da&&!(typeof a.da.isDisposed=="function"&&a.da.isDisposed())},Bwa=function(a,b){a.complete=!0;a.t6=_.Li();a.Sa&&(_.fa.clearTimeout(a.Sa),a.Sa=null);Awa(a)&&(a.errorOccurred&&a.da.xR&&a.da.xR(a),a.da.X7&&a.da.X7(a,b))},Cwa=function(){if(!(window.chrome&&window.chrome.runtime&&window.chrome.runtime.getManifest&&window.chrome.runtime.getManifest()))throw Error("Bc");};Vr.prototype.getUrl=function(){return String(this.ha.clone())};
Vr.prototype.oa=function(a,b){_.pla(this.ha,a,b)};Vr.prototype.Da=function(a,b){this.Ma||(this.Ma=new _.Mm);Array.isArray(b)||(b=[String(b)]);_.ta(_.Yo,this.aa)||(this.aa="POST");_.ola(this.Ma,a,b)};var Dwa=function(a,b,c){if(b instanceof _.Mm){var d=b.getKeys();_.Ia(d);for(var e=0;e<d.length;e++){var f=d[e],g=b.Ok(f);c?a.Da(f,g):a.oa(f,g)}}else _.lm(b,function(m,p){c?this.Da(p,m):this.oa(p,m)},a)};var Ewa=function(a,b,c,d){_.Qn.call(this,(d?"data_b:":"data:")+b);this.datatype=b;this.request=a;this.data=c;this.aa=void 0};_.J(Ewa,_.Qn);var Gwa=function(){this.ha=[];this.oa={};Fwa(this,1E3)},Fwa=function(a,b,c){c?a.wS=b:(b=Math.min(3E5,Math.max(b,1E3)),a.wS=Math.round(.85*b)+Math.round(.3*b*Math.random()))};_.h=Gwa.prototype;_.h.UJ=function(){return this.JL};_.h.VV=function(){return this.JL==this.KL};_.h.aK=function(){return this.oa};_.h.getError=function(){return this.wp};_.h.eb=function(a){this.wp=a};_.h.reset=function(){this.da=null;this.eb(null)};_.h.z_=0;_.h.KL=-1;_.h.JL=0;_.h.WC=0;_.h.gv=0;_.h.z9=0;_.h.wS=0;var hs=function(a,b){_.Qn.call(this,a);b&&(this.aa=b)};_.J(hs,_.Qn);_.Ni(Wva,_.ka);_.Ni(Wr,_.bo);var Hwa="_/reporthttp4xxerror";_.h=Wr.prototype;_.h.uw=null;_.h.sP="READY";_.h.cG=1;_.h.Y_=!1;_.h.dispose=function(){for(var a=0;a<this.ha.length;a++){var b=this.ha[a].getContext();b.gv&&(_.fa.clearTimeout(b.gv),b.gv=0)}this.isDisposed()||(Wr.ff.dispose.call(this),this.Ia.clear(),this.uw&&(_.fa.clearTimeout(this.uw),this.uw=null));for(a=0;a<this.oa.length;a++)this.oa[a].dispose();this.ha.length=this.aa.length=0;this.Xa.dispose()};
var is=function(a,b){var c={};c.Ata=(0,_.th)(a.Bta,a);c.HS=(0,_.th)(a.HS,a);c.VL=(0,_.th)(a.VL,a);c.Ina=(0,_.th)(a.Pi,a);c.tR=(0,_.th)(a.jh,a);c.VV=(0,_.th)(a.hb,a);c.hAa=(0,_.th)(a.Lc,a);c.UJ=(0,_.th)(a.Cc,a);c.xBa=(0,_.th)(a.wa,a);c.HP=(0,_.th)(a.HP,a);b.aa=c;a.oa.push(b)};Wr.prototype.getTransports=function(){return this.oa.concat()};Wr.prototype.send=function(a){this.isDisposed()?Iwa(this,a,107):(this.dispatchEvent(new hs("i",a)),this.Ia.enqueue(a),Jwa(this))};Wr.prototype.getState=function(){return this.sP};
Wr.prototype.abort=function(a,b){Kwa(this,a,b)};
var Kwa=function(a,b,c){c=typeof c==="number"?c:100;_.ta(a.aa,b)?(b.getContext().z_=c,(a=b.getContext())&&a.da&&a.da.abort(a.z_)):a.Ia.remove(b)&&Iwa(a,b,c)},Mwa=function(a,b){var c=null,d={},e=_.Si(a.oa,function(q){var r=_.Ga(q);d[r]=q.I0(b);return!!d[r]});_.Ka(e,(0,_.th)(a.xb,null,d,a.oa));for(var f=0,g=e.length,m=0;m<g&&!c;m++){var p=e[m];if(!p.ha){c=p;break}p=d[_.Ga(p)];if(m==g-1||p>d[_.Ga(e[m+1])])for(;!c&&f<=m;)if(c=e[f++],Lwa(a,c)<a.cG)if(c=c.clone())is(a,c);else{if(p==1)throw Error("Ec");
}else throw Error("Fc");}return c};Wr.prototype.xb=function(a,b,c,d){var e=_.Ga(c),f=_.Ga(d);return a[e]<a[f]?1:a[e]>a[f]?-1:c.ha&&!d.ha?1:!c.ha&&d.ha?-1:_.qa(b,d)-_.qa(b,c)};var Lwa=function(a,b){var c=0;b=b.constructor;a=a.oa;for(var d=a.length,e=0;e<d;e++)a[e].constructor===b&&c++;return c};Wr.prototype.HP=function(a){if(this.Ma.size!==0)for(var b=Array.from(this.Ma.keys()),c=0;c<b.length;c++){var d=b[c],e=this.Ma.get(d);a.oa(d,e);this.Ma.delete(d)}};
var js=function(a,b){switch(b){case "ACTIVE":case "WAITING_FOR_RETRY":case "RETRY_TIMER":if(a.aa.length==0)throw Error("Hc`"+b);}if(b!=a.sP&&(a.sP=b,a.dispatchEvent(new hs("h")),a.oc))a.oc.onStateChanged()},Jwa=function(a){if(a.Sa&&(a.sP=="READY"||a.cG!==1)){var b=_.Lva(a.Ia);b&&a.aa.length<a.cG&&(_.Kva(a.Ia),b.xb=new Gwa,a.aa.push(b),Nwa(a,b))}},Nwa=function(a,b){b.getUrl();var c=b.getContext();c.JL=0;c.KL=-1;c=_.Li();b.i7==-1&&(b.i7=c);b.Y8=c;b.hI++;try{js(a,"ACTIVE");try{var d=b.getContext();d.z_=
0;var e=d.da;if(!e){e=Mwa(a,b);if(!e)throw Error("Gc`"+b);e.ha=!0;d.da=e}d.aa=null;e.transfer(b);a.uw||(a.uw=Yr("Jc",a.H9,3E4,a))}catch(f){throw f;}}catch(f){throw f;}};Wr.prototype.jh=function(a,b){this.tR(a,b)};Wr.prototype.tR=function(a,b){for(var c=a.getContext(),d=0;d<b.length;d++){var e=b[d];c.JL++;var f=e[0];f!==cs.messageId&&c.ha.push(e);c.UJ()==1&&Owa(a);f==cs.messageId?Pwa(this,a,e):f==as.messageId?Qwa(a,e):f==bs.messageId&&(Rwa(a,new bs(e)),this.wa(a))}};
Wr.prototype.Pi=function(a,b){var c=a.getContext();c.JL++;var d=b[0];c.WC&&(_.fa.clearTimeout(c.WC),c.WC=0);d!==cs.messageId&&c.ha.push(b);c.UJ()==1&&Owa(a);d==cs.messageId?Pwa(this,a,b):d==as.messageId?Qwa(a,b):d==bs.messageId?(Rwa(a,new bs(b)),this.wa(a)):(b=a.getContext(),a=Yr("Jc",_.pg(this.wa,a),1,this),b.WC=a)};
var Owa=function(a){try{_.Li()}catch(b){Qr("Exception in onFirstArray_",b),a.getContext().aa=b}},Pwa=function(a,b,c){c=new cs(c);(c=_.bl(c,1,_.Tc))&&a.Ya&&c!=a.Ya&&(b.getContext().aa=Error(106))},Qwa=function(a,b){try{var c=new as(b),d=new wwa(c);a.bT=d}catch(e){Qr("Exception in handleDebugInfoArray_",e),a.getContext().aa=e}},Rwa=function(a,b){var c=a.getContext(),d=_.Zk(b,1,_.Tc);c.KL=d;var e;((e=_.Eh(_.Dk(b,4,_.Tc)))!=null?e:0)>0&&(b=_.Eh(_.Dk(b,4,_.Tc)),a.wd=b)};
Wr.prototype.wa=function(a){var b=a.getContext();b.WC&&(_.fa.clearTimeout(b.WC),b.WC=0);var c=b.ha,d=b.aK();if(c.length&&(b.ha=[],b.oa={},b=a?a.getContext():null,!b||!b.aa))try{for(var e=0;e<c.length;e++){var f=c[e];this.dispatchEvent(new Ewa(a,f[0],(0,_.ik)(f),!0))}var g=(0,_.ik)(c);a&&Awa(a)&&a.da.Mna&&a.da.Mna(a,c);this.dispatchEvent(new Ewa(a,"aa",g));for(f=0;f<c.length;f++){var m=c[f],p=(0,_.ik)(m),q=m[0];if(a)if(q==_.$r.messageId){var r=_.Ova(_.$r,(0,_.ik)(m)),t=_.Zk(r,5,_.Tc);if(t>=500&&t<
700){var v=new Sr(a,t,!1,a.hI);if(dwa(v)){b.eb(v);a=b;var x=new Wva;a.aa=x;break}}g=a;g.oc=r;Awa(g)&&g.da.xR&&g.da.xR(g)}else g=a,Awa(g)&&g.da.Y7&&g.da.Y7(g,q,m,d);this.dispatchEvent(new Ewa(a,q,p))}}catch(y){y instanceof Xr||Qr("Exception in processArrays",y),b&&(b.aa=y)}};Wr.prototype.hb=function(a){return a.getContext().VV()};Wr.prototype.Cc=function(a){return a.getContext().UJ()};Wr.prototype.Lc=function(a){return a.getContext().KL};
var Swa=function(a,b){if(a.Y_&&b.getContext().z9<=0&&(a=b.Lc,a>=400&&a<500)){var c=_.yma(document,"base"),d=null;c.length&&(d=c[0].href);c=d||window.location.href;d=b.ha.clone();c instanceof _.Dg||(c=_.Pm(c));d instanceof _.Dg||(d=_.Pm(d));c=c.resolve(d);b=_.Bm(Hwa,"url",c,"status",a,"traceid",b.bT.da);_.Zo(b,null,"POST");_.lg(Error("Ic`"+c+"`"+a))}};
Wr.prototype.VL=function(a,b){b=b===void 0?{}:b;var c=a.getContext();c.oa=b;this.wa(a);Swa(this,a);var d=c.aa;if(d||!c.VV()){var e;if(d){if(d instanceof Xr)return a.getUrl(),b=c.wS,_.ta(this.aa,a)&&(Fwa(a.getContext(),b,!0),_.va(this.ha,a),a.getContext().gv=-1,js(this,"WAITING_FOR_RETRY")),!0;d instanceof Wva?e=c.getError():e=new Sr(a,d.message==106?106:12,!0)}else b="Missing data arrays. Expected "+c.KL+", received "+c.UJ(),e=new Sr(a,103,!1,a.hI,b),this.Cb&&Twa(a);Uwa(this,a,e);return!1}a.errorOccurred=
!1;a.Xa=null;a.rP=-1;Bwa(a,b);this.dispatchEvent(new hs("j",a));_.xa(this.ha,a);js(this,"WAITING_FOR_READY");return!0};Wr.prototype.HS=function(a,b){this.Cb&&b.aa==103&&Twa(a);this.wa(a);Swa(this,a);Uwa(this,a,b)};var Uwa=function(a,b,c){b.getContext().eb(c);b.bT=xwa;dwa(c)?(_.va(a.ha,b),b.getContext().gv=-1,b="WAITING_FOR_RETRY"):(dwa(c),_.xa(a.ha,b),Iwa(a,b,c),b="WAITING_FOR_READY");js(a,b)};_.h=Wr.prototype;
_.h.Bta=function(a){var b=_.oa(this.aa,function(c){return c.getContext().da==a});_.ta(this.ha,b)||(a.ha=!1,b.getContext().reset(),_.xa(this.aa,b));this.uw&&(_.fa.clearTimeout(this.uw),this.uw=null);_.Ma(this.ha,this.Jpa,this);this.aa.length<this.cG&&(js(this,"READY"),Jwa(this))};_.h.Jpa=function(a){var b=a.getContext();if(b.gv==-1){var c=_.Fg(a.ha,"f.retries");Dwa(a,{"f.retries":(c?Number(c):0)+1},!1);c=b.wS;var d=_.Li()+c;b.z9=d;a=Yr("Jc",(0,_.th)(this.Cqa,this,a),c);b.gv=a;Fwa(b,2*c);js(this,"RETRY_TIMER")}};
_.h.Cqa=function(a){var b=a.getContext();b.gv&&(_.fa.clearTimeout(b.gv),b.gv=0);Nwa(this,a)};_.h.H9=function(){this.uw=Yr("Jc",this.H9,3E4,this);this.j6()};
_.h.j6=function(){if(this.aa.length!=0&&this.Da)for(var a=this.aa.length,b=0;b<a;b++){var c=this.aa[b],d=_.Li(),e=c.Y8;if(e>-1&&d-e>6E4)if(d=this.Da,e=Date.now(),e-d.PZ>d.ha?(d.aa.gE||(navigator!==null&&"onLine"in navigator&&!navigator.onLine?(d.PZ=e-d.ha+1E3,Yr("sc",(0,_.th)(d.J9,d,!1),0)):(e=new _.Dg("//www.google.com/images/cleardot.gif"),_.Om(e),d.aa.oa=e,d.aa.start())),d=!0):d=!1,d)break;else this.Da.w9||Kwa(this,c,1)}};
var Twa=function(a){a.oa("nrt",a.hI);var b=a.getContext().da;b instanceof es&&(b=_.bp(b.Tm),b!=null&&a.Da("rhma",b))};Wr.prototype.disable=function(){this.Sa=!1};var Iwa=function(a,b,c){typeof c==="number"&&(c=new Sr(b,c));a.dispatchEvent(new hs("k",b,c));b.errorOccurred=!0;b.Xa=c;Bwa(b)};var Vwa=_.ri(["BqgkJe","OWXEXe"]),Wwa=_.ri(["IE0Oi","cESSm","OWXEXe"]),Xwa=_.ri(["xK4gQc","V1GM4b","OWXEXe"]),ks=function(a,b,c,d,e){this.Da=[];this.Vb=this.Xa=!1;this.Ia=b;this.wa=c;this.oa=d;this.da=e;this.Sa=a.wa;this.ha=new _.rf;this.Na=new _.rf(this.Ya.bind(this));this.Ma=a;this.aa=new Vr(this.da.Ota?a.ha:a.aa);_.Im(this.aa.ha,this.Ia);this.aa.aa=this.da.method;if(typeof this.da.host==="string"){var f=_.om(this.da.host)[1]||null;var g=_.wm(_.om(this.da.host)[3]||null,!0);var m=Number(_.om(this.da.host)[4]||
null)||null}f=f||this.da.scheme;typeof f==="string"&&(a=this.aa,Cwa(),_.Fm(a.ha,f));g=g||this.da.domain;typeof g==="string"&&(f=this.aa,Cwa(),_.Gm(f.ha,g));typeof m==="number"&&(g=this.aa,Cwa(),_.Hm(g.ha,m));m=this.aa;(g=!_.ta(_.Yo,this.aa.aa))&&_.ta(_.Yo,m.aa)?m.aa="GET":g||_.ta(_.Yo,m.aa)||(m.aa="POST");_.gs(m);m.Vb=g;Ywa(this);if(this.wa){if(_.ta(_.Yo,this.aa.aa)){m=this.wa;try{var p=m instanceof HTMLFormElement}catch(q){p=typeof m==="object"&&m.nodeType===1&&typeof m.style==="object"&&typeof m.ownerDocument===
"object"&&m.tagName.toLowerCase()==="form"}if(p){p=this.aa;_.gs(p);p.VR=!1;p=this.aa;m=this.wa;_.gs(p);if(p.VR)throw Error("Cc");p.wa=m}else this.wa instanceof _.w?this.aa.Da("f.req",this.wa.Ce()):Dwa(this.aa,this.wa,!0)}else Dwa(this.aa,this.wa,!1);this.da.yw&&(_.zwa(this.aa,!1),p=this.aa,_.gs(p),p.Ya=!0)}Zwa(this);this.Md=null};ks.prototype.send=function(){return this.Ma.sendRequest(this)};
var $wa=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d].messageId]=b[d];b=[];d=[];for(var e=0;e<a.length;e++){var f=a[e];if(f instanceof _.w){var g=c[f.constructor.messageId];f instanceof _.$r?d.push(f):g&&b.push(f)}else{var m=Sva(f);if(g=c[m])m=m===as.messageId||m===bs.messageId||m===_.$r.messageId,f=_.Ova(g,m?(0,_.ik)(f):f),b.push(f),m||(a[e]=f)}}return{zM:b,fF:d}};ks.prototype.xb=function(a){a=a.data;for(var b=0;b<a.length;b++){var c=a[b];if(c instanceof Sr)throw c;}return a};
ks.prototype.wd=function(a){a=a.data;if(this.oa.length===0)return null;var b=$wa(a,this.oa);if(b.zM.length===0&&b.fF.length===0)throw new gwa(this.oa,a,this.Ia);return _.za(b.zM,b.fF)};ks.prototype.Cb=function(a){a=a.data;if(this.oa.length===0)return null;var b=$wa(a,this.oa),c=b.zM;b=b.fF;if(c.length===0&&b.length===0)throw new gwa(this.oa,a,this.Ia);if(c.length===1&&b.length===0)return c[0];if(c.length===0&&b.length===1)throw b[0];throw new fwa(this.oa,a,this.Ia);};ks.prototype.getUrl=function(){return this.aa.getUrl()};
_.ls=function(a,b){Dwa(a.aa,b,!1)};ks.prototype.cancel=function(){this.ha.cancel()};
var axa=function(a,b){_.Ma(a.Sa,function(c){var d=[];Array.isArray(d)||(d=[d]);d=$wa(b,d).fF;if(d.length)try{c.da(d)}catch(e){if(e instanceof Xr)throw this.Vb=!0,new hwa;throw e;}},a)},bxa=function(a,b){if(a.da.yw){b=[b];axa(a,b);b=$wa(b,a.oa);var c;b.zM.length>0?c=b.zM[0]:b.fF.length>0&&(c=b.fF[0]);if(c){var d;_.kh(Nva(Vwa,Rva((d=c.constructor.messageId)!=null?d:"unknown")),function(){return a.da.yw(c)})}}else a.Da.push(b)},Ywa=function(a){var b={},c=a.Na;b.xR=function(d){if(!c.da){var e=d.Xa;e?
c.aa(e):bxa(a,d.oc)}};b.X7=function(d,e){if(!c.da){d="unknown";a.Da.length>0&&(a.Da[0]instanceof _.w?d=a.Da[0].constructor.messageId:Array.isArray(a.Da[0])&&(d=Sva(a.Da[0])));var f;_.kh(Nva(Wwa,a.Da.length,Rva((f=d)!=null?f:"unknown")),function(){c.callback({data:a.Da,responseHeaders:e});return c})}};b.Y7=function(d,e,f){bxa(a,f)};b.eCa=!0;a.aa.da=b},Zwa=function(a){_.Ma(a.Sa,function(b){b.aa&&_.vj(this.ha,b.aa,b)},a);_.vj(a.ha,function(b){b.send();return _.wj(a.Na.oq(),function(c){c instanceof _.qj&&
a.Na.cancel()})});a.da.yw?_.vj(a.ha,function(){return null}):(_.vj(a.ha,function(b){axa(a,b.data)}),a.da.mka?_.vj(a.ha,a.wd,a):a.da.g$?_.vj(a.ha,a.xb,a):_.vj(a.ha,a.Cb,a));_.wj(a.ha,a.hb,a)},cxa=function(a){return _.kh(Nva(Xwa,Rva(a.aa.aa),Rva(a.aa.ha.da)),function(){a.ha.callback(a.aa);return a.ha})};
ks.prototype.hb=function(a){if(a instanceof hwa||this.Vb&&this.da.yw){a=_.Fg(this.aa.ha,"f.retries");a=(a?Number(a):0)+1;if(a>100)throw new _.Zr("TooManyRetries",102,this.Ia,"There was an error after several retries.");var b=_.ms(this.Ma,this.Ia,this.wa,this.oa,this.da);_.ls(b,{"f.retries":a});return this.Ma.sendRequest(b)}if(!(a instanceof _.qj)){if(!this.da.g$&&a instanceof Sr){b=a.aa;if(b==100&&this.Xa)return new _.qj(this.ha);throw new _.Zr("TransportError",b,this.Ia,"There was an error during the transport or processing of this request.",
a);}throw a;}};ks.prototype.Ya=function(){this.aa&&(this.Xa=!0,this.aa.abort())};ks.prototype.toString=function(){return this.aa.getUrl()};var ns=function(a){es.call(this,"j",a||null)};_.J(ns,es);ns.prototype.I0=function(a){var b=a.wa;return b&&Pva(b)?0:a.VR&&!a.Ya?.9:.5};ns.prototype.clone=function(){var a=new ns,b=this.Sa;a.oa=this.oa;a.Sa=b;return a};ns.prototype.e8=function(a){var b=_.bp(a);b=b.substring(b.indexOf("\n"));a=this.da;try{var c=window.JSON.parse(b)}catch(d){c=new Sr(a,10);this.aa.HS(a,c);return}Array.isArray(c)&&this.aa.tR(a,c[0]);this.aa.VL(a)};
ns.prototype.lK=function(a){var b=_.bp(a);b=b.substring(b.indexOf("\n"));try{var c=window.JSON.parse(b)}catch(d){}Array.isArray(c)?(a=this.da,this.aa.tR(a,c[0]),this.aa.VL(a)):es.prototype.lK.call(this,a)};var dxa;dxa={mka:!1,domain:void 0,yw:null,method:"POST",g$:!1,scheme:void 0,host:void 0,Ota:!1};_.os=function(a,b,c,d){_.bo.call(this);this.Da=null;this.wa=[];this.Ia=null;this.eJ=dxa;this.yE=null;_.bo.call(this);b||(b=new Wr,is(b,new ns));this.ha=b;c||(c=new Wr,is(c,new ns));this.aa=c;this.ha=b||null;this.aa=c||null;this.Da=d||null};_.J(_.os,_.bo);_.os.prototype.XQ=function(){return _.Ob(this.eJ)};
var exa=function(a){var b=_.Pr()+"/reporthttp4xxerror";a.ha&&(a.ha.Y_=!0);a.aa&&(a.aa.Y_=!0);b&&(Hwa=b)};_.os.prototype.oa=function(a){_.ph(this,a);this.wa.push(a)};_.os.prototype.makeRequest=function(a,b,c,d){return this.sendRequest(_.ms(this,a,b,c,d))};_.ms=function(a,b,c,d,e){var f=[],g={};e||d&&(typeof d==="function"||Array.isArray(d))?(d&&(f=Array.isArray(d)?d:[d]),e&&(g=e)):d&&(g=d);d=f;e=a.XQ();_.Qb(e,g||{});return new ks(a,b,c||null,d,e)};
_.os.prototype.sendRequest=function(a){this.Ia||(this.Ia=a);return cxa(a)};_.os.prototype.Nd=function(){_.ia(this.ha);_.ia(this.aa);_.ia(this.Da);_.bo.prototype.Nd.call(this)};_.os.prototype.initialize=function(a){a=a.get(_.Lna).aa;var b=this.ha;b.Da=a;b.Da&&b.Xa.listen(b.Da,"g",b.j6);this.Da=null};_.ff(_.Nl,_.os);_.Eb().Bl(function(a){var b=new _.rf,c=new _.os(a);c.yE=function(){c.yE=null;return b};_.nq(a,_.Nl,c);c.initialize(a);var d=new _.fs;is(c.ha,d);is(c.aa,d);_.fxa(c);c.ha.cG=10;c.aa.cG=10;exa(c);_.Iva(a.get(_.Mna));c.oa(new twa(_.dp(_.ug("FdrFJe"))));c.oa(new qwa(_.dp(_.ug("cfb2h"))));c.oa(new swa("e","mods","jsmode","deb","opt","route","hotswaps"));a=window.location.href;_.Em(a,"hl")||(a=_.Bm(a,"hl","tr"));c.oa(new rwa("e hl gl jsmode deb opt route hotswaps _hostType authuser pageId duul nuul".split(" "),
a));b.callback()});_.fxa=function(){};
_.k("LEikZe");

_.l();
}catch(e){_._DumpException(e)}
}).call(this,this.default_AccountsSignInUi);
// Google Inc.
