"use strict";this.default_AccountsSignInUi=this.default_AccountsSignInUi||{};(function(_){var window=this;
try{
var fMa;fMa=function(a,b){a=_.Vf(a,!1);return{enabled:a,dD:a?_.ska(_.ip(b(),_.dMa)):eMa()}};
_.hMa=function(){var a=fMa(_.ug("xwAfE"),function(){return _.ug("UUFaWc")}),b=fMa(_.ug("xnI9P"),function(){return _.ug("u4g7r")}),c,d,e,f;return(f=gMa)!=null?f:gMa=Object.freeze({isEnabled:function(g){return g===-1||_.Vf(_.ug("iCzhFc"),!1)?!1:a.enabled||b.enabled},FQ:(c=_.dp(_.ug("y2FhP")))!=null?c:void 0,aW:(d=_.dp(_.ug("MUE6Ne")))!=null?d:void 0,uu:(e=_.dp(_.ug("cfb2h")))!=null?e:void 0,Jq:_.gp(_.ug("yFnxrf"),-1),y6:_.zoa(_.ug("fPDxwd")).map(function(g){return _.gp(g,0)}).filter(function(g){return g>
0}),ACa:_.Vf(_.ug("vJQk6"),!1),vaa:a,faa:b})};_.dMa=function(a){this.Ea=_.u(a)};_.J(_.dMa,_.w);var eMa=function(a){return function(){var b;(b=a[_.Ad])||(b=new a,_.Lc(b.Ea),b=a[_.Ad]=b);return b}}(_.dMa),gMa;
_.k("p3hmRc");
var lNa=function(a,b){var c=_.Mr(_.Or()),d=_.xDa(),e;c=_.jNa(_.hNa((new _.Ay(a,c)).ox(_.py(new _.oy,b.y6)),(e=b.uu)!=null?e:""));d&&d.length>0&&_.iNa(c,d.map(function(p){return _.Sd(p)}));switch(a){case 1957:var f=3;break;case 2082:f=2;break;case 1884:f=1;break;case 2649:f=0}var g,m;return new kNa(c.build(),(g=b.aW)!=null?g:"",f,(m=b.FQ)!=null?m:"")};var kNa=function(a,b,c,d){this.transport=a;this.aa=b;this.da=c;this.FQ=d;this.ha=Number(Date.now()).toString(36)+Math.random().toString(36).slice(2)};_.Ey=function(){_.Ss.call(this);this.config=_.hMa();var a=this.config.Jq;this.config.isEnabled(a)&&(this.aa=lNa(a,this.config))};_.J(_.Ey,_.Kt);_.Ey.Ca=_.Kt.Ca;_.Lt(_.Era,_.Ey);
_.l();
_.mNa=function(a,b,c){var d=b.aa().rsa(a.ha);a.aa!==void 0&&d.pha(a.aa);a.FQ&&d.nsa(a.FQ);a.da&&d.osa(a.da);var e,f,g=(e=_.Eb())==null?void 0:(f=e.Ma)==null?void 0:_.Ko(f.oa,"k");g&&d.ssa(g);b.da(c);a.transport.Ci(b);a.transport.flush()};_.Fy=function(a){this.Ea=_.u(a)};_.J(_.Fy,_.w);_.h=_.Fy.prototype;_.h.getUrl=function(){return _.Sk(this,3)};_.h.pha=function(a){_.L(this,5,a)};_.h.nsa=function(a){_.L(this,7,a)};_.h.osa=function(a){_.kl(this,8,a)};_.h.rsa=function(a){return _.L(this,9,a)};
_.h.ssa=function(a){_.L(this,10,a)};_.Gy=function(a){this.Ea=_.u(a)};_.J(_.Gy,_.w);_.Gy.prototype.aa=function(){return _.ny(this,_.Fy,5)};_.Gy.prototype.da=function(a){_.Zf(this,_.dMa,18,a)};
var nNa=_.fa.URL,oNa,pNa,rNa,qNa;try{new nNa("http://example.com"),oNa=!0}catch(a){oNa=!1}pNa=oNa;
rNa=function(a){var b=_.oo("A");try{_.Ue(b,_.fb(a));var c=b.protocol}catch(e){throw Error("Jd`"+a);}if(c===""||c===":"||c[c.length-1]!=":")throw Error("Jd`"+a);if(!qNa.has(c))throw Error("Jd`"+a);if(!b.hostname)throw Error("Jd`"+a);var d=b.href;a={href:d,protocol:b.protocol,username:"",password:"",hostname:b.hostname,pathname:"/"+b.pathname,search:b.search,hash:b.hash,toString:function(){return d}};qNa.get(b.protocol)===b.port?(a.host=a.hostname,a.port="",a.origin=a.protocol+"//"+a.hostname):(a.host=
b.host,a.port=b.port,a.origin=a.protocol+"//"+a.hostname+":"+a.port);return a};
_.sNa=function(a){if(pNa){try{var b=new nNa(a)}catch(d){throw Error("Jd`"+a);}var c=qNa.get(b.protocol);if(!c)throw Error("Jd`"+a);if(!b.hostname)throw Error("Jd`"+a);b.origin=="null"&&(a={href:b.href,protocol:b.protocol,username:"",password:"",host:b.host,port:b.port,hostname:b.hostname,pathname:b.pathname,search:b.search,hash:b.hash},a.origin=c===b.port?b.protocol+"//"+b.hostname:b.protocol+"//"+b.hostname+":"+b.port,b=a)}else b=rNa(a);return b};
qNa=new Map([["http:","80"],["https:","443"],["ws:","80"],["wss:","443"],["ftp:","21"]]);
_.k("LvGhrf");
var uNa=function(a){if(_.fa&&_.fa.performance&&_.fa.performance.memory){var b=_.fa.performance.memory;if(b){var c=new tNa;isNaN(b.jsHeapSizeLimit)||_.ry(c,1,Math.round(b.jsHeapSizeLimit).toString());isNaN(b.totalJSHeapSize)||_.ry(c,2,Math.round(b.totalJSHeapSize).toString());isNaN(b.usedJSHeapSize)||_.ry(c,3,Math.round(b.usedJSHeapSize).toString());_.Zf(a,tNa,1,c)}}},xNa=function(a){if(vNa()){var b=performance.getEntriesByType("navigation");if(b&&b.length){var c=new Hy;if(b=b[0]){switch(b.type){case "navigate":c.Yb(1);
break;case "reload":c.Yb(2);break;case "back_forward":c.Yb(3);break;case "prerender":c.Yb(4);break;default:c.Yb(0)}var d=_.el(c,2,Math.round(b.startTime));d=_.el(d,3,Math.round(b.fetchStart));d=_.el(d,4,Math.round(b.domainLookupStart));d=_.el(d,5,Math.round(b.domainLookupEnd));d=_.el(d,6,Math.round(b.connectStart));d=_.el(d,7,Math.round(b.connectEnd));d=_.el(d,8,Math.round(b.requestStart));d=_.el(d,9,Math.round(b.responseStart));d=_.el(d,10,Math.round(b.responseEnd));var e=wNa(Math.round(b.domInteractive));
d=_.el(d,11,e);e=wNa(Math.round(b.domComplete));d=_.el(d,12,e);d=_.el(d,13,Math.round(b.loadEventStart));_.el(d,14,Math.round(b.loadEventEnd))}_.Zf(a,Hy,8,c)}}},wNa=function(a){return Number.isFinite(a)?a:null},zNa=function(a){if(vNa()){var b=performance.getEntriesByType("resource");if(b&&b.length){for(var c=new yNa,d=0,e=0,f=0,g=0,m=0,p=0,q=0,r=0,t=0,v=0,x=0;x<b.length;x++){var y=b[x],A=y.responseEnd-y.startTime;if(A>=0)switch(y.initiatorType){case "css":d++;e+=A;break;case "img":f++;g+=A;break;
case "script":m++;p+=A;break;case "link":q++;r+=A;break;default:t++,v+=A}}d&&(b=_.el(c,1,d),_.el(b,2,Math.round(e/d)));f&&(d=_.el(c,3,f),_.el(d,4,Math.round(g/f)));m&&(f=_.el(c,5,m),_.el(f,6,Math.round(p/m)));q&&(m=_.el(c,7,q),_.el(m,8,Math.round(r/q)));t&&(q=_.el(c,9,t),_.el(q,10,Math.round(v/t)));_.Zf(a,yNa,10,c)}}},ANa=function(){var a;return window.PerformanceObserver&&((a=window.PerformanceObserver.supportedEntryTypes)==null?void 0:a.includes("paint"))},CNa=function(a){if(vNa()){var b=performance.getEntriesByType("paint");
if(b&&b.length){var c=_.mk(a,Iy,11)?_.K(a,Iy,11):new Iy;BNa(b,c);_.Zf(a,Iy,11,c)}}},BNa=function(a,b){for(var c=0;c<a.length;c++){var d=a[c],e=Math.round(d.startTime);d.name!=="first-paint"||_.Gk(b,1)!=null?d.name!=="first-contentful-paint"||_.Gk(b,2)!=null||_.el(b,2,e):_.el(b,1,e)}},vNa=function(){return _.fa.performance&&_.fa.performance.getEntriesByType?!0:!1},Jy=function(a,b){DNa.get(a)||DNa.set(a,new b);return DNa.get(a)},tNa=function(a){this.Ea=_.u(a)};_.J(tNa,_.w);
var Hy=function(a){this.Ea=_.u(a)};_.J(Hy,_.w);Hy.prototype.getType=function(){return _.Tk(this,1)};Hy.prototype.Yb=function(a){return _.kl(this,1,a)};var Iy=function(a){this.Ea=_.u(a)};_.J(Iy,_.w);var yNa=function(a){this.Ea=_.u(a)};_.J(yNa,_.w);var Ky=function(a){this.Ea=_.u(a)};_.J(Ky,_.w);var ENa=function(a){this.Ea=_.u(a)};_.J(ENa,_.w);var FNa=function(a){this.Ea=_.u(a)};_.J(FNa,_.w);var GNa=function(a){this.Ea=_.u(a)};_.J(GNa,_.w);var HNa=function(a){this.Ea=_.u(a)};_.J(HNa,_.w);
HNa.prototype.Ua=function(){return _.Sk(this,2)};HNa.prototype.getUrl=function(){return _.Sk(this,3)};var INa=function(a){this.Ea=_.u(a)};_.J(INa,_.w);var Ly=function(a){this.Ea=_.u(a)};_.J(Ly,_.w);var JNa=function(){this.aa=0;this.da=[]};var My=function(){var a=performance.getEntriesByType("navigation")[0];if(a&&a.responseStart>0&&a.responseStart<performance.now())return a};var KNa=function(a){if(document.readyState==="loading")return"loading";var b=My();if(b){if(a<b.domInteractive)return"loading";if(b.domContentLoadedEventStart===0||a<b.domContentLoadedEventStart)return"dom-interactive";if(b.domComplete===0||a<b.domComplete)return"dom-content-loaded"}return"complete"};var LNa=function(a){var b="";try{for(var c;((c=a)==null?void 0:c.nodeType)!==9;){var d=a;if(d.id)var e="#"+d.id;else{var f=d.nodeName;e=[d.nodeType===1?f.toLowerCase():f.toUpperCase().replace(/^#/,"")].concat(_.of(Array.from(d.classList).sort())).join(".")}var g=e;if(b.length+g.length>99)return b||g;b=b?g+">"+b:g;if(d.id)break;a=d.parentNode}}catch(m){}return b};var DNa=new WeakMap;var MNa=-1,Ny=function(a){addEventListener("pageshow",function(b){b.persisted&&(MNa=b.timeStamp,a(b))},!0)};var Oy=function(a,b,c,d){var e,f;return function(g){if(b.value>=0&&(g||d)){var m;if((f=b.value-((m=e)!=null?m:0))||e===void 0)e=b.value,b.WA=f,g=b.value,b.xra=g>c[1]?"poor":g>c[0]?"needs-improvement":"good",a(b)}}};var NNa=function(a){requestAnimationFrame(function(){return requestAnimationFrame(function(){return a()})})};var Py=function(){var a,b;return(b=(a=My())==null?void 0:a.activationStart)!=null?b:0};var Qy=function(a,b){b=b===void 0?-1:b;var c=My(),d="navigate";MNa>=0?d="back-forward-cache":c&&(document.prerendering||Py()>0?d="prerender":document.wasDiscarded?d="restore":c.type&&(d=c.type.replace(/_/g,"-")));return{name:a,value:b,xra:"good",WA:0,entries:[],id:"v5-"+Date.now()+"-"+(Math.floor(Math.random()*(9E12-1))+1E12),navigationType:d}};var Ry=function(a,b,c){c=c===void 0?{}:c;try{if(PerformanceObserver.supportedEntryTypes.includes(a)){var d=new PerformanceObserver(function(e){Promise.resolve().then(function(){b(e.getEntries())})});d.observe(Object.assign({},{type:a,buffered:!0},c));return d}}catch(e){}};var ONa=function(a){var b=!1;return function(){b||(a(),b=!0)}};var Sy=-1,PNa=function(a){document.visibilityState==="hidden"&&Sy>-1&&(Sy=a.type==="visibilitychange"?a.timeStamp:0,removeEventListener("visibilitychange",PNa,!0),removeEventListener("prerenderingchange",PNa,!0))},QNa=function(){addEventListener("visibilitychange",PNa,!0);addEventListener("prerenderingchange",PNa,!0)},RNa=function(){if(Sy<0){var a=Py(),b,c;Sy=(c=document.prerendering?void 0:(b=globalThis.performance.getEntriesByType("visibility-state").filter(function(d){return d.name==="hidden"&&
d.startTime>a})[0])==null?void 0:b.startTime)!=null?c:document.visibilityState!=="hidden"||document.prerendering?Infinity:0;QNa();Ny(function(){setTimeout(function(){Sy=document.visibilityState!=="hidden"||document.prerendering?Infinity:0;QNa()})})}return{get k7(){return Sy}}};var SNa=function(a){document.prerendering?addEventListener("prerenderingchange",function(){return a()},!0):a()};var TNa=[1800,3E3],UNa=function(a,b){b=b===void 0?{}:b;SNa(function(){var c=RNa(),d=Qy("FCP"),e=Ry("paint",function(g){g=_.n(g);for(var m=g.next();!m.done;m=g.next())m=m.value,m.name==="first-contentful-paint"&&(e.disconnect(),m.startTime<c.k7&&(d.value=Math.max(m.startTime-Py(),0),d.entries.push(m),f(!0)))});if(e){var f=Oy(a,d,TNa,b.ev);Ny(function(g){d=Qy("FCP");f=Oy(a,d,TNa,b.ev);NNa(function(){d.value=performance.now()-g.timeStamp;f(!0)})})}})};var VNa=[.1,.25],WNa=function(a,b){b=b===void 0?{}:b;UNa(ONa(function(){var c=Qy("CLS",0),d=Jy(b,JNa),e=function(m){m=_.n(m);for(var p=m.next();!p.done;p=m.next()){var q=void 0,r=d;p=p.value;if(!p.hadRecentInput){var t=r.da[0],v=r.da.at(-1);r.aa&&t&&v&&p.startTime-v.startTime<1E3&&p.startTime-t.startTime<5E3?(r.aa+=p.value,r.da.push(p)):(r.aa=p.value,r.da=[p]);(q=r.ha)==null||q.call(r,p)}}d.aa>c.value&&(c.value=d.aa,c.entries=d.da,g())},f=Ry("layout-shift",e);if(f){var g=Oy(a,c,VNa,b.ev);document.addEventListener("visibilitychange",
function(){document.visibilityState==="hidden"&&(e(f.takeRecords()),g(!0))});Ny(function(){d.aa=0;c=Qy("CLS",0);g=Oy(a,c,VNa,b.ev);NNa(function(){return g()})});setTimeout(g)}}))};var XNa=function(a){return a.reduce(function(b,c){return b.value>c.value?b:c})},YNa=function(a){return a.find(function(b){var c;return((c=b.node)==null?void 0:c.nodeType)===1})||a[0]},ZNa=function(a,b){b=b===void 0?{}:b;b=Object.assign({},b);var c=Jy(b,JNa),d=new WeakMap;c.ha=function(e){var f;if(e==null?0:(f=e.sources)==null?0:f.length)if(e=YNa(e.sources)){var g;f=((g=b.o7)!=null?g:LNa)(e.node);d.set(e,f)}};WNa(function(e){var f={};if(e.entries.length){var g=XNa(e.entries),m;(g==null?0:(m=g.sources)==
null?0:m.length)&&(m=YNa(g.sources))&&(f={lpa:d.get(m),mpa:g.startTime,npa:g.value,OAa:m,NAa:g,XZ:KNa(g.startTime)})}e=Object.assign(e,{attribution:f});a(e)},b)};var $Na=function(a,b){b=b===void 0?{}:b;UNa(function(c){var d={sN:0,j7:c.value,XZ:KNa(MNa)};if(c.entries.length){var e=My(),f=c.entries.at(-1);e&&(d=Math.max(0,e.responseStart-(e.activationStart||0)),d={sN:d,j7:c.value-d,XZ:KNa(c.entries[0].startTime),v9:e,Sza:f})}c=Object.assign(c,{attribution:d});a(c)},b)};var aOa=0,bOa=Infinity,cOa=0,dOa=function(a){a=_.n(a);for(var b=a.next();!b.done;b=a.next())b=b.value,b.interactionId&&(bOa=Math.min(bOa,b.interactionId),aOa=(cOa=Math.max(cOa,b.interactionId))?(cOa-bOa)/7+1:0)},eOa,fOa=function(){var a;return eOa?aOa:(a=performance.interactionCount)!=null?a:0};var gOa=0,hOa=function(){this.aa=[];this.da=new Map};hOa.prototype.Da=function(){gOa=fOa();this.aa.length=0;this.da.clear()};hOa.prototype.oa=function(){return this.aa[Math.min(this.aa.length-1,Math.floor((fOa()-gOa)/50))]};
var iOa=function(a,b){var c;(c=a.ha)==null||c.call(a,b);if(b.interactionId||b.entryType==="first-input"){var d=a.aa.at(-1);if((c=a.da.get(b.interactionId))||a.aa.length<10||b.duration>d.Ux){c?b.duration>c.Ux?(c.entries=[b],c.Ux=b.duration):b.duration===c.Ux&&b.startTime===c.entries[0].startTime&&c.entries.push(b):(c={id:b.interactionId,entries:[b],Ux:b.duration},a.da.set(c.id,c),a.aa.push(c));a.aa.sort(function(f,g){return g.Ux-f.Ux});if(a.aa.length>10)for(b=a.aa.splice(10),b=_.n(b),d=b.next();!d.done;d=
b.next())a.da.delete(d.value.id);var e;(e=a.wa)==null||e.call(a,c)}}};var jOa=function(a){var b=globalThis.requestIdleCallback||setTimeout;document.visibilityState==="hidden"?a():(a=ONa(a),b(a),document.addEventListener("visibilitychange",a,{once:!0}))};var kOa=[200,500],lOa=function(a,b){b=b===void 0?{}:b;globalThis.PerformanceEventTiming&&"interactionId"in PerformanceEventTiming.prototype&&SNa(function(){"interactionCount"in performance||eOa||(eOa=Ry("event",dOa,{type:"event",buffered:!0,durationThreshold:0}));var c=Qy("INP"),d=Jy(b,hOa),e=function(p){jOa(function(){for(var q=_.n(p),r=q.next();!r.done;r=q.next())iOa(d,r.value);(q=d.oa())&&q.Ux!==c.value&&(c.value=q.Ux,c.entries=q.entries,m())})},f,g=Ry("event",e,{durationThreshold:(f=b.durationThreshold)!=
null?f:40});var m=Oy(a,c,kOa,b.ev);g&&(g.observe({type:"first-input",buffered:!0}),document.addEventListener("visibilitychange",function(){document.visibilityState==="hidden"&&(e(g.takeRecords()),m(!0))}),Ny(function(){d.Da();c=Qy("INP");m=Oy(a,c,kOa,b.ev)}))})};var mOa=function(a,b){b=b===void 0?{}:b;b=Object.assign({},b);var c=Jy(b,hOa),d=[],e=[],f=0,g=new WeakMap,m=new WeakMap,p=!1,q=function(){var x=c.aa.map(function(R){return g.get(R.entries[0])}),y=e.length-50;e=e.filter(function(R,U){return U>=y?!0:x.includes(R)});for(var A=new Set,C=_.n(e),G=C.next();!G.done;G=C.next()){G=G.value;G=r(G.startTime,G.processingEnd);G=_.n(G);for(var H=G.next();!H.done;H=G.next())A.add(H.value)}var N=d.length-1-50;d=d.filter(function(R,U){return R.startTime>f&&U>N?!0:
A.has(R)});p=!1};c.ha=function(x){var y=x.startTime+x.duration;f=Math.max(f,x.processingEnd);for(var A=e.length-1;A>=0;A--){var C=e[A];if(Math.abs(y-C.renderTime)<=8){var G=C;G.startTime=Math.min(x.startTime,G.startTime);G.processingStart=Math.min(x.processingStart,G.processingStart);G.processingEnd=Math.max(x.processingEnd,G.processingEnd);G.entries.push(x);break}}G||(G={startTime:x.startTime,processingStart:x.processingStart,processingEnd:x.processingEnd,renderTime:y,entries:[x]},e.push(G));(x.interactionId||
x.entryType==="first-input")&&g.set(x,G);p||(jOa(q),p=!0)};c.wa=function(x){if(!m.get(x)){var y,A=((y=b.o7)!=null?y:LNa)(x.entries[0].target);m.set(x,A)}};var r=function(x,y){for(var A=[],C=_.n(d),G=C.next();!G.done;G=C.next())if(G=G.value,!(G.startTime+G.duration<x)){if(G.startTime>y)break;A.push(G)}return A},t=function(x){var y;if((y=x.YZ)!=null&&y.length){y=x.D8;for(var A=x.noa,C=x.processingDuration,G=0,H=0,N=0,R=0,U,Z,T=_.n(x.YZ),ea=T.next();!ea.done;ea=T.next()){ea=ea.value;H=H+ea.startTime+
ea.duration-ea.styleAndLayoutStart;ea=_.n(ea.scripts);for(var ra=ea.next();!ra.done;ra=ea.next()){ra=ra.value;var ya=ra.startTime+ra.duration;if(!(ya<y)){ya-=Math.max(y,ra.startTime);var Ra=ra.duration?ya/ra.duration*ra.forcedStyleAndLayoutDuration:0;G+=ya-Ra;H+=Ra;ya>R&&(Z=ra.startTime<y+A?"input-delay":ra.startTime>=y+A+C?"presentation-delay":"processing-duration",U=ra,R=ya)}}}T=(T=x.YZ.at(-1))?T.startTime+T.duration:0;T>=y+A+C&&(N=x.y9-T);U&&Z&&(x.Bpa={entry:U,bCa:Z,EAa:R});x.vta=G;x.wta=H;x.uta=
N;x.xta=x.y9-y-G-H-N}},v=function(x){var y=x.entries[0],A=g.get(y),C=y.processingStart,G=Math.max(y.startTime+y.duration,C),H=Math.min(A.processingEnd,G);A=A.entries.sort(function(U,Z){return U.processingStart-Z.processingStart});var N=r(y.startTime,H),R=c.da.get(y.interactionId);y={poa:m.get(R),qoa:y.name.startsWith("key")?"keyboard":"pointer",D8:y.startTime,y9:G,yBa:A,YZ:N,noa:C-y.startTime,processingDuration:H-C,qBa:G-H,XZ:KNa(y.startTime),Bpa:void 0,vta:void 0,wta:void 0,uta:void 0,xta:void 0};
t(y);return Object.assign(x,{attribution:y})};Ry("long-animation-frame",function(x){d=d.concat(x);p||(jOa(q),p=!0)});lOa(function(x){x=v(x);a(x)},b)};var nOa=function(){};var oOa=[2500,4E3],pOa=function(a,b){b=b===void 0?{}:b;SNa(function(){var c=RNa(),d=Qy("LCP"),e=Jy(b,nOa),f=function(t){b.ev||(t=t.slice(-1));t=_.n(t);for(var v=t.next();!v.done;v=t.next()){v=v.value;var x=void 0;(x=e.aa)==null||x.call(e,v);v.startTime<c.k7&&(d.value=Math.max(v.startTime-Py(),0),d.entries=[v],m())}},g=Ry("largest-contentful-paint",f);if(g){var m=Oy(a,d,oOa,b.ev);for(var p=ONa(function(){f(g.takeRecords());g.disconnect();m(!0)}),q=_.n(["keydown","click","visibilitychange"]),r=q.next();!r.done;r=
q.next())addEventListener(r.value,function(){return jOa(p)},{capture:!0,once:!0});Ny(function(t){d=Qy("LCP");m=Oy(a,d,oOa,b.ev);NNa(function(){d.value=performance.now()-t.timeStamp;m(!0)})})}})};var qOa=function(a,b){b=b===void 0?{}:b;b=Object.assign({},b);var c=Jy(b,nOa),d=new WeakMap;c.aa=function(f){if(f.element){var g,m=((g=b.o7)!=null?g:LNa)(f.element);d.set(f,m)}};var e=function(f){var g={sN:0,t$:0,u$:0,Z6:f.value};if(f.entries.length){var m=My();if(m){var p=m.activationStart||0,q=f.entries.at(-1),r=q.url&&performance.getEntriesByType("resource").filter(function(v){return v.name===q.url})[0];g=Math.max(0,m.responseStart-p);var t=Math.max(g,r?(r.requestStart||r.startTime)-p:0);p=Math.min(f.value,
Math.max(t,r?r.responseEnd-p:0));g={target:d.get(q),sN:g,t$:t-g,u$:p-t,Z6:f.value-p,v9:m,QAa:q};q.url&&(g.url=q.url);r&&(g.RAa=r)}}return Object.assign(f,{attribution:g})};pOa(function(f){f=e(f);a(f)},b)};var rOa=[800,1800],sOa=function(a){document.prerendering?SNa(function(){return sOa(a)}):document.readyState!=="complete"?addEventListener("load",function(){return sOa(a)},!0):setTimeout(a)},tOa=function(a,b){b=b===void 0?{}:b;var c=Qy("TTFB"),d=Oy(a,c,rOa,b.ev);sOa(function(){var e=My();e&&(c.value=Math.max(e.responseStart-Py(),0),c.entries=[e],d(!0),Ny(function(){c=Qy("TTFB",0);d=Oy(a,c,rOa,b.ev);d(!0)}))})};var uOa=function(a,b){b=b===void 0?{}:b;tOa(function(c){var d={uaa:0,W5:0,V6:0,u6:0,q$:0};if(c.entries.length){d=c.entries[0];var e=d.activationStart||0,f=Math.max((d.workerStart||d.fetchStart)-e,0),g=Math.max(d.domainLookupStart-e,0),m=Math.max(d.connectStart-e,0);e=Math.max(d.connectEnd-e,0);d={uaa:f,W5:g-f,V6:m-g,u6:e-m,q$:c.value-e,v9:d}}c=Object.assign(c,{attribution:d});a(c)},b)};var vOa=function(a,b){this.ha=a;this.dD=b;this.aa=new _.Fy;a=new _.Gy;this.msg=_.Zf(a,_.Fy,5,this.aa);this.da=!1},yOa;
vOa.prototype.init=function(a){var b=this,c;return _.Di(function(d){if(d.aa==1)return a.url&&(c=_.sNa(a.url),_.L(b.aa,3,c.hostname),_.L(b.aa,6,c.pathname)),a.A_&&_.L(b.aa,4,a.A_),ANa()&&wOa(b),xOa(b),_.ui(d,new Promise(function(e){document.readyState!=="complete"?_.Vn(window,"load",function(){setTimeout(e,0)}):setTimeout(e,0)}),2);uNa(b.msg);CNa(b.msg);xNa(b.msg);zNa(b.msg);b.da=!0;return d.return(yOa(b))})};_.zOa=function(a,b){a.da=!0;b(a.msg)};
yOa=function(a){return _.Di(function(b){return b.return(Promise.race([AOa(),new Promise(function(c){return void setTimeout(c,3E4)})]).then(function(){a.flush();yOa(a)}))})};vOa.prototype.flush=function(){if(this.da){_.mNa(this.ha,this.msg,this.dD);var a=new _.Gy;this.msg=_.Zf(a,_.Fy,5,this.aa);this.da=!1}};
var AOa=function(){return new Promise(function(a){var b=_.Wn(window,"pagehide",function(c){c.persisted==null||c.persisted||(_.$n(b),a())})})},xOa=function(a){Ty(a,ZNa,function(b,c){var d=_.ny(b,Ky,9);_.hl(d,1,c.value);c.attribution&&(b=_.ny(b,Ly,14),b=_.ny(b,ENa,1),b=_.hl(b,1,c.value),b=_.L(b,2,c.attribution.lpa),b=_.el(b,3,c.attribution.mpa),_.hl(b,4,c.attribution.npa))});Ty(a,$Na,function(b,c){var d=_.ny(b,Ky,9);_.el(d,2,Math.round(c.value));c.attribution&&(b=_.ny(b,Ly,14),b=_.ny(b,FNa,2),b=_.el(b,
1,Math.round(c.value)),b=_.el(b,2,Math.round(c.attribution.sN)),_.el(b,3,Math.round(c.attribution.j7)))});Ty(a,qOa,function(b,c){var d=_.ny(b,Ky,9);_.el(d,4,Math.round(c.value));c.attribution&&(b=_.ny(b,Ly,14),b=_.ny(b,HNa,4),b=_.el(b,1,Math.round(c.value)),b=_.L(b,2,c.attribution.target),b=_.el(b,4,Math.round(c.attribution.sN)),b=_.el(b,5,Math.round(c.attribution.t$)),b=_.el(b,6,Math.round(c.attribution.u$)),_.el(b,7,Math.round(c.attribution.Z6)))});Ty(a,uOa,function(b,c){var d=_.ny(b,Ky,9);_.el(d,
5,Math.round(c.value));c.attribution&&(b=_.ny(b,Ly,14),b=_.ny(b,INa,5),b=_.el(b,1,Math.round(c.value)),b=_.el(b,2,Math.round(c.attribution.uaa+c.attribution.W5)),b=_.el(b,3,Math.round(c.attribution.V6)),b=_.el(b,4,Math.round(c.attribution.u6)),_.el(b,5,Math.round(c.attribution.q$)))});Ty(a,mOa,function(b,c){var d=_.ny(b,Ky,9);_.el(d,6,Math.round(c.value));c.attribution&&(b=_.ny(b,Ly,14),b=_.ny(b,GNa,6),b=_.el(b,1,Math.round(c.value)),b=_.L(b,2,c.attribution.poa),b=_.el(b,3,c.attribution.D8),_.L(b,
4,c.attribution.qoa))})},Ty=function(a,b,c){b(function(d){return void _.zOa(a,function(e){return void c(e,d)})})},wOa=function(a){var b=new window.PerformanceObserver(function(c){_.zOa(a,function(d){BNa(c.getEntries(),_.ny(d,Iy,11))});b.disconnect()});try{b.observe({type:"paint",buffered:!0})}catch(c){}};_.Uy=function(a){_.Ss.call(this);this.aa=new Map;var b=_.hMa();(a=a.Fa.qS.aa)&&b.vaa.enabled&&(this.da=new vOa(a,b.vaa.dD))};_.J(_.Uy,_.Kt);_.Uy.Ca=function(){return{Fa:{qS:_.Ey}}};_.Uy.prototype.init=function(a){var b=this;return _.Di(function(c){if(BOa||!b.da)return c.return();BOa=!0;return c.return(b.da.init(a))})};var BOa=!1;_.Lt(_.MIa,_.Uy);
_.l();
_.k("RqjULd");
var COa=function(a){this.Ea=_.u(a)};_.J(COa,_.w);var DOa=function(a,b){return _.L(a,1,b)},EOa=function(a,b){return _.L(a,2,b)},FOa=function(a,b){return _.el(a,3,b)},GOa=function(a){this.Ea=_.u(a)};_.J(GOa,_.w);var HOa=function(a,b,c,d,e){var f=FOa(EOa(DOa(new COa,b),c),d);e!==void 0&&_.el(f,4,e);_.zOa(a,function(g){g=_.ny(g,GOa,13);_.Ak(g,1,COa,f)})},IOa=function(a){_.Ss.call(this);this.aa=a.Fa.Wta};_.J(IOa,_.Kt);IOa.Ca=function(){return{Fa:{Wta:_.Uy}}};
IOa.prototype.init=function(){var a=this,b,c;return _.Di(function(d){if(JOa)return d.return();JOa=!0;b=new KOa(a.aa);return(c=!!_.vh(_.vp).aa)?d.return(_.Nf(a,{Fa:{te:_.xp}}).then(function(e){e=e.Fa.te;var f=e.getCurrentView();f=f?f.aa.da.aa.getName():"";a.aa.init({url:e.Oi(),A_:f});b.register(e)},function(){a.aa.init({url:"",A_:window.cc_aid})})):d.return()})};var JOa=!1,KOa=function(a){this.aa=a};
KOa.prototype.register=function(a){this.te=a;a=this.te.Nx();a.listen(_.Bx,this.ha,!1,this);a.listen(_.LIa,this.da,!1,this)};KOa.prototype.ha=function(a){if(a){var b,c=((b=this.te.getCurrentView())==null?void 0:b.aa.da.aa.getName())||"";b=this.aa;a=a.request.Pd.aa.aa;b.aa.has(a)||b.aa.set(a,{Tqa:c,navigationStart:performance.now(),redirectCount:0})}};
KOa.prototype.da=function(a){if(a){var b=a.request.Pd.aa;a=this.aa;var c=b.aa;b=b.getName();var d=a.aa.get(c);if(d){var e;(e=a.da)==null||HOa(e,d.Tqa,b,performance.now()-d.navigationStart,d.redirectCount);a.aa.delete(c)}}};_.Lt(_.NIa,IOa);
_.l();
}catch(e){_._DumpException(e)}
}).call(this,this.default_AccountsSignInUi);
// Google Inc.
