"use strict";this.default_AccountsSignInUi=this.default_AccountsSignInUi||{};(function(_){var window=this;
try{
_.VTa=_.z("wg1P6b",[_.xz,_.wz,_.Hp]);
_.k("wg1P6b");
var lcb;lcb=_.ri(["aria-"]);
_.dE=function(a){_.X.call(this,a.La);this.Ma=this.wa=this.da=this.viewportElement=this.Na=null;this.Rc=a.Fa.cj;this.Ya=a.Fa.focus;this.zd=a.Fa.zd;this.aa=this.Kj();a=-1*parseInt(_.$p(this.Kj().el(),"marginTop")||"0",10);var b=parseInt(_.$p(this.Kj().el(),"marginBottom")||"0",10);this.Xa={top:a,right:0,bottom:b,left:0};a=_.Vf(this.getData("isMenuDynamic"),!1);b=_.Vf(this.getData("isMenuHoisted"),!1);this.Ia=a?1:b?2:0;this.oa=!1;this.Da=1;if(this.Ia!==1){this.da=this.Ua("U0exHf").children().first();if(!this.da){var c;
a=(c=this.Ba().wb("jsname"))!=null?c:"";throw Error("Ie`"+a);}this.Lk(mcb(this,this.da.el()))}_.oB(this.Ba())&&(c=this.Ba().el(),a=this.Me.bind(this),c.__soy_skip_handler=a)};_.J(_.dE,_.X);_.dE.Ca=function(){return{Fa:{cj:_.cB,focus:_.UA,zd:_.Pt}}};_.dE.prototype.FB=function(a){var b=a.source;this.Na=b;var c;((c=a.data)==null?0:c.PC)?(a=a.data.PC,this.Da=a==="MOUSE"||a==="TOUCH"?1:2):this.Da=b.Da||b.Ma?1:2;ncb(this)};
_.dE.prototype.gk=function(a){a=a.event;var b=a.keyCode;b===40?this.Da=2:b===38&&(this.Da=3);return b===40||b===38?(a.preventDefault(),ncb(this),!1):!0};var ncb=function(a){_.Di(function(b){a.da?(a.fw().wa=a.Da,a.Dh()):a.trigger("dcnbp");_.vi(b)})};_.dE.prototype.Dh=function(){ocb(this);this.ha.Af()?this.ha.close():(this.Ia===2&&(pcb(this,this.da.el()),qcb(this)),this.ha.open())};
_.dE.prototype.PB=function(a){if(a.source!==this.ha)return!0;this.Na&&this.Na.Tl?_.gB(this.Rc,this.aa,{Tl:this.Na.Tl()}):_.gB(this.Rc,this.aa);return!0};_.dE.prototype.Ss=function(){rcb(this);return!0};var rcb=function(a){_.Di(function(b){if(a.Qj())return b.return();a.Sd().activeElement!==a.aa.el()&&_.hB(a.Rc,a.aa);a.oa&&(a.Ba().el().removeAttribute("aria-owns"),a.Ma&&_.k2a(a.Ma,a.aa));a.Ia===1&&scb(a);a.Ia===2&&(tcb(a,a.da.el()),qcb(a),ucb(a));_.vi(b)})};_.h=_.dE.prototype;_.h.hx=function(){return!0};
_.h.Qj=function(){var a,b;return(b=(a=this.ha)==null?void 0:a.Af())!=null?b:!1};_.h.Ms=function(){if(!(this.ha instanceof _.ZD))throw Error("Je");return this.ha};_.h.fw=function(){ocb(this);return this.ha};_.h.ew=function(){return this.Ua("WjL7X").children().rd(0)};_.h.Kj=function(){return this.aa?this.aa:vcb(this)};_.h.dispose=function(){_.X.prototype.dispose.call(this);this.oa&&scb(this)};
var vcb=function(a){a=a.ew();if(a.wb("aria-haspopup")==="menu")return a;var b=_.fq(a,'[aria-haspopup="menu"]').first();if(b)return b;_.Vf(a.getData("isTooltipWrapper"),!1)&&(a=a.children().rd(0));_.Vf(a.getData("isTouchWrapper"),!1)&&(a=a.children().rd(0));return a},pcb=function(a,b){a.wa=new _.eq(document.createElement("div"));b.getAttribute("id")||b.setAttribute("id",_.wg((new _.eq(b)).Js("menuUid")));a.Ba().el().setAttribute("aria-owns",b.getAttribute("id"));a.wa.append(b);var c=a.Sd().body;_.WD(c)?
_.XD(c,a.wa.el()):c.appendChild(a.wa.el());a.Or(b,a.Ua("U0exHf"));a.oa=!0;a.da=_.Gt(b)},tcb=function(a,b){a.Ua("U0exHf").empty().append(b);a.oa=!1;a.da=_.Gt(b)};_.dE.prototype.Sa=function(a){var b=b===void 0?{}:b;this.da&&scb(this);b.Uoa?pcb(this,a):tcb(this,a);b.viewportElement&&(this.viewportElement=b.viewportElement);mcb(this,a)};
var mcb=function(a,b){return _.vj(a.Ih(b),function(c){a.ha=c;qcb(a);return a.ha})},qcb=function(a){a.fw().wa=a.Da;var b=a.ha;b.aa=a.aa;if(!a.oa&&!b.jt()){var c=a.Xa;b.da.top=c.top||0;b.da.right=c.right||0;b.da.bottom=c.bottom||0;b.da.left=c.left||0}b.Sa=a.oa;a.viewportElement&&(b.viewportElement=a.viewportElement);a.oa&&(a.Ma=b instanceof _.ZD?b.Gg().Ba():b.Ba(),_.j2a(a.Ya,a.Ma,a.aa))},scb=function(a){a.da&&(a.da.remove(),a.LE(),a.da=null,ucb(a))},ucb=function(a){a.wa&&(a.wa.remove(),a.LE(),a.wa=
null)},ocb=function(a){if(!a.ha)throw a=a.Ba().wb("jsname"),Error(a?"MenuButtonController: MenuSurfaceController not found (jsname="+a+").":"MenuButtonController: MenuSurfaceController not found.");};_.dE.prototype.Me=function(a,b){wcb(this,b);return!0};
var wcb=function(a,b){_.Di(function(c){var d=a.ew().el();if(!d)throw Error("Ke");a.zd.ti(d,b.getContent());a.aa=vcb(a);if(a.Ia!==1&&b.data.menu){if(!a.da)throw Error("Le");a.zd.ti(a.da.el(),b.data.menu);d=a.Ia===2&&a.oa?a.wa.children().rd(0):a.Ua("U0exHf").children().rd(0);a.da.el()!==d.el()&&(a.Qj()&&a.oa&&ucb(a),a.Sa(d.el()))}_.Bt([_.Sa(lcb)],a.Kj().el(),"aria-expanded",a.Qj().toString());_.vi(c)})};_.Y(_.dE.prototype,"A5GSIb",function(){return this.dispose});_.Y(_.dE.prototype,"uh8wMe",function(){return this.Kj});
_.Y(_.dE.prototype,"UeYGad",function(){return this.ew});_.Y(_.dE.prototype,"SeiAcc",function(){return this.fw});_.Y(_.dE.prototype,"K3J0i",function(){return this.Ms});_.Y(_.dE.prototype,"tLCEwd",function(){return this.Qj});_.Y(_.dE.prototype,"NSsOUb",function(){return this.hx});_.Y(_.dE.prototype,"li9Srb",function(){return this.Ss});_.Y(_.dE.prototype,"oNPcuf",function(){return this.PB});_.Y(_.dE.prototype,"SYZktf",function(){return this.Dh});_.Y(_.dE.prototype,"uYT2Vb",function(){return this.gk});
_.Y(_.dE.prototype,"aj0Jcf",function(){return this.FB});_.Hu(_.VTa,_.dE);
_.l();
}catch(e){_._DumpException(e)}
}).call(this,this.default_AccountsSignInUi);
// Google Inc.
